aquarius_formations.settings:
  type: config_object
  label: 'Parametres Aquarius Formations'
  mapping:
    enable_attendance_indicator:
      type: boolean
      label: 'Activer l''indicateur d''assiduite'
    evaluation_input_mode:
      type: string
      label: 'Mode de saisie des evaluations'
